jobs:
  include:
    - language: java
      before_script:
        - cd usbtherm-ui
        
    - language: c
      before_script:
        - cd usbtherm-linux
      install:
        - sudo apt-get update -qq
        - sudo apt-get install -y linux-headers-generic
        - sudo ln -s /usr/src/$(uname -r) /lib/modules/$(uname -r)/build
    
      script:
        - make

